### ISSUE TITLE
Error in extracting images from PDF file - detectPdfText function

### ISSUE THREAD

**Issue by 10001oleg** [GoogleCloudPlatform/cloud-vision#159]
**"aws-sdk": "^2.437.0"
nodeJS 8
Env - Google Cloud Function, unlimited workers, clean logs**
**it works it 80% cases**

severity:  "ERROR"  
 textPayload:  "Error: Error in extracting images from PDF file gs://******/******.pdf
    at Operation._unpackResponse (/srv/node_modules/google-gax/build/src/longrunning.js:211:31)
    at noCallbackPromise.currentCallPromise_.then.responses (/srv/node_modules/google-gax/build/src/longrunning.js:197:18)
    at <anonymous>"  

**// CODE EXAMPLE**
`const detectPdfText = async () => {
    const vision = require('@google-cloud/vision').v1;
    const client = new vision.ImageAnnotatorClient();

    const inputConfig = {
      // Supported mime_types are: 'application/pdf' and 'image/tiff'
      mimeType: 'application/pdf',
      gcsSource: {
        uri: gcsSourceUri,
      },
    };
    const outputConfig = {
      gcsDestination: {
        uri: gcsDestinationUri,
      },
    };
    const features = [{type: 'DOCUMENT_TEXT_DETECTION'}];
    const request = {
      requests: [
        {
          inputConfig: inputConfig,
          features: features,
          outputConfig: outputConfig,
        },
      ],
    };

    const [operation] = await client.asyncBatchAnnotateFiles(request);
    const [filesResponse] = await operation.promise();
    const destinationUri =
      filesResponse.responses[0].outputConfig.gcsDestination.uri;
    console.log('Json saved to: ' + destinationUri);

  };
  await detectPdfText();`
    

**Please help me ASAP**

**Comment by 10001oleg** [comment]
### **nobody? really?**

**Comment by 10001oleg** [comment]
wtf

**Comment by 10001oleg** [comment]
**कृपया मेरी मदद करें**
