### ISSUE TITLE
Make sure Travis passes for non-branch pull requests

### ISSUE THREAD

**Issue by tswast** [GoogleCloudPlatform/cloud-vision#50]
Ran into this in https://github.com/GoogleCloudPlatform/cloud-vision/pull/49.

Maven fails on non-branch PRs. https://travis-ci.org/GoogleCloudPlatform/cloud-vision/jobs/116719540

```
Running com.google.cloud.vision.samples.facedetect.FaceDetectAppIT
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.252 sec <<< FAILURE! - in com.google.cloud.vision.samples.facedetect.FaceDetectAppIT
detectFaces_withFace_returnsAtLeastOneFace(com.google.cloud.vision.samples.facedetect.FaceDetectAppIT)  Time elapsed: 0.173 sec  <<< ERROR!
java.lang.IllegalArgumentException: no JSON input found
    at com.google.cloud.vision.samples.facedetect.FaceDetectAppIT.setUp(FaceDetectAppIT.java:44)
detectFaces_badImage_throwsException(com.google.cloud.vision.samples.facedetect.FaceDetectAppIT)  Time elapsed: 0.001 sec  <<< ERROR!
java.lang.IllegalArgumentException: no JSON input found
    at com.google.cloud.vision.samples.facedetect.FaceDetectAppIT.setUp(FaceDetectAppIT.java:44)
```

Go fails on non-branch PRs https://travis-ci.org/GoogleCloudPlatform/cloud-vision/jobs/116719539

```
++go vet ./go/...
++'[' -f /home/travis/build/GoogleCloudPlatform/cloud-vision/client-secret.json ']'
++go test -v ./go/...
=== RUN   TestLabel
--- FAIL: TestLabel (0.13s)
    Error Trace:    label_test.go:40
    Error:      Received unexpected error "google: error getting credentials using GOOGLE_APPLICATION_CREDENTIALS environment variable: unexpected end of JSON input"
```

**Comment by tswast** [comment]
Obsolete.
