### ISSUE TITLE
TypeError(repr(o) + " is not JSON serializable")

### ISSUE THREAD

**Issue by trieb** [GoogleCloudPlatform/cloud-vision#55]
Running the example faces.py using google-api-python-client (1.5.0) in python (3.5.1)
I get the following error `TypeError(repr(o) + " is not JSON serializable")`

```
Traceback (most recent call last):
  File "C:/git/code/python/scripts/GoogleVisionAPI/faces.py", line 83, in <module>
    main('face-input.jpg', 'out.jpg')
  File "C:/git/code/python/scripts/GoogleVisionAPI/faces.py", line 68, in main
    faces = detect_face(image)
  File "C:/git/code/python/scripts/GoogleVisionAPI/faces.py", line 41, in detect_face
    request = service.images().annotate(body={'requests': batch_request,})
  File "C:\Anaconda3\lib\site-packages\googleapiclient\discovery.py", line 743, in method
    actual_path_params, actual_query_params, body_value)
  File "C:\Anaconda3\lib\site-packages\googleapiclient\model.py", line 149, in request
    body_value = self.serialize(body_value)
  File "C:\Anaconda3\lib\site-packages\googleapiclient\model.py", line 258, in serialize
    return json.dumps(body_value)
  File "C:\Anaconda3\lib\json\__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "C:\Anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Anaconda3\lib\json\encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
```

**Comment by trieb** [comment]
Got it working using the following modification to the original code: 

```python
image_content = face_file.read()
    batch_request = [{
        'image': {
            #'content': base64.b64encode(image_content)
            'content': str(base64.b64encode(image_content).decode("utf-8"))
            },
        'features': [{
            'type': 'FACE_DETECTION',
            'maxResults': max_results,
            }]
        }]
```

**Comment by tswast** [comment]
Thanks for your feedback.

We needed something like this in the other samples, too. https://github.com/GoogleCloudPlatform/cloud-vision/pull/28 I'll get a PR ready, thanks.

**Comment by tswast** [comment]
This should be fixed by #58.

**Comment by trieb** [comment]
Great!

**Comment by hardik-emiprotechnologies** [comment]
@trieb 
As per your solution, the image data gets converted to 'String', which in turn is not in a format as 'binary' value. This is causing problem for me, as we are writing this image value to remote Shopify Instance.
Any idea on this?
